### ISSUE TITLE
The app Crashes

### ISSUE THREAD

**Issue by randavictor** [oodesign/merge-duplicate-symbols#132]
The app crash and sketch quits when I press on merge or when I select on a duplicate to search for similar symbols.

**Comment by oodesign** [comment]
Hi @randavictor ,

We've identified several performance issues (most of them related with dealing with big files with lots of instances, symbols, and styles). You may find a bit more on [Issue 131](https://github.com/oodesign/merge-duplicate-symbols/issues/131) and [Issue 113](https://github.com/oodesign/merge-duplicate-symbols/issues/113).

We just released v8.1.0, that should be way faster processing symbols than the previous versions (we're still working on text&layer styles performance).

May you give it a try and let us know how it worked for you?

Thanks!

**Comment by jpawlowicz** [comment]
hello @oodesign, app is crashing for me too, no matter what option I use, it always freezes sketch. I need to clean up a big file and it worked for me for a while and it stopped few weeks ago.

**Comment by oodesign** [comment]
Hi @jpawlowicz ,

To investigate a bit further your issue, may you please send us the Merge Duplicates logs? Logs don't contain any sensitive information about your design file, it's just plugin processing related information. You can do so by:

1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with
3. Merge Duplicates logs are disabled by default. You may enable them by going to Plugins > Merge duplicates... > Settings , and switching on the logging ability.
4. Run the Merge Duplicates command you were having issues with (Merge Symbols, Merge Text Styles or Merge Layer Styles, or any of their variants)
5. Proceed as usual until you experience the issue you described. **Don't quit Sketch yet** (this is important, as Sketch logs are deleted when you quit the app).
6. Logs will be stored by this point. May you please [send us](mailto:oscar@oodesign.me) your log file so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰

**Comment by jpawlowicz** [comment]
Hi, I have sent you the log file, hope this will help! :)

**Comment by jpawlowicz** [comment]
@oodesign something weird happened, I left sketch running for another 20 minutes and it unfroze and worked. But that's way too long to use it at work. I'll try to capture a longer log and also send it to you.

**Comment by oodesign** [comment]
Hi @jpawlowicz ,

Thanks for sending us both logs. They really help!

We've identified several performance issues (most of them related with dealing with big files, or with big symbols with lots of overrides) since we moved the plugin to use the official Sketch API (which we needed to keep up with the most recent Sketch changes, like tint overrides, and color variables). Your case seems to fit in this scenario.

We're putting all of our effort (and working with Sketch) on fixing them, and hope to get Merge Duplicates as efficient as it used to be as soon as possible. This is our primary focus currently.

A couple of weeks ago we released v8.1.0, that addresses performance issues when merging symbols. We're still working on layer & text styles performance improvements, though, so merging styles may still be sluggish.

I'll make sure to keep you updated when we're able to release a fix for it.

**Comment by randavictor** [comment]
Hi @oodesign , 
it's better after the v8.1.0 update in selecting the similarities, it's fast, but it still crash when I press on merge symbols, specially if it's more than 10 merges... it keep working and suddenly the whole sketch crash!

**Comment by oodesign** [comment]
Hi @randavictor ,

Sorry to hear that :(

What MacOS version and Sketch version are you on?

May I ask you to send us the Merge Duplicates logs too? Logs don't contain any sensitive information about your design file, it's just plugin processing related information. You can do so by:

1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with
3. Merge Duplicates logs are disabled by default. You may enable them by going to Plugins > Merge duplicates... > Settings , and switching on the logging ability.
4. Run the Merge Duplicates command you were having issues with (Merge Symbols, Merge Text Styles or Merge Layer Styles, or any of their variants)
5. Proceed as usual until you experience the issue you described. **Don't quit Sketch yet** (this is important, as Sketch logs are deleted when you quit the app).
6. Logs will be stored by this point. May you please [send us](mailto:oscar@oodesign.me) your log file so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰

**Comment by randavictor** [comment]
Hi @oodesign ,
I've sent you the logo now, am using **Mojave 10.14.6** , Sketch **68.2**

**Comment by oodesign** [comment]
Hi @randavictor ,

Thanks for sending us the logs. They help a lot!

Per the logs you sent us we see that the plugin seems to work correctly, but causes a memory issue due to how many instances and overrides it's processing. This may be caused by the plugin itself, by how Sketch handles memory, or by the device itself.

In order to investigate further the issue, may I ask you to please [send us](mailto:oscar@oodesign.me) your design file (and related libraries)?

Your files are and will remain confidential. We ensure they will only be used to investigate the issue you're describing, deleted after closing it, and never stored or used for any other means.

Also please feel free to use the sharing platform you prefer to send us the files, if you don't want to send them via email. Just [let us know](mailto:oscar@oodesign.me) the details to get them.

Thanks a lot!

**Comment by randavictor** [comment]
Hi @oodesign ,
I've sent you the file.

hope things get better soon.

Thank you!

**Comment by oodesign** [comment]
Hi @randavictor ,

Thanks for sending us the design file. We'll deep dive on it and come back to you asap.

Thank you!

**Comment by oodesign** [comment]
Hi @randavictor ,

Wow, we have to admit that this file IS huge 😅 .

### Long story short

I'm afraid Merge Duplicates can't handle that many merges in a row (in your device). I'd suggest to, instead of tackling all the duplicates altogether, split the merge in smaller groups (merge the first 10, then trigger Merge Duplicates again and merge the next 10, and so on...).

### And... the long story

We see that you have 600+ symbols and 900+ artboards, with a total of 40.000+ symbol instances in them.

Merge Duplicates scans all of those symbols looking for duplicates (which is pretty quick), but also needs to process where the symbols are applied as symbol overrides, which technically means having to process those 40K symbol instances too. You may notice that the initial merge window takes a while to load because of this (when typically should take - at most - a few seconds).

After the initial load everything should be pretty smooth in the UI until you hit "Merge".

When merging several duplicates (duplicates of SymbolA, duplicates of SymbolB, duplicates of SymbolC, ...) they get merged by order. We call each each of these merges **"a merge"**.  When merging several duplicates, we have to consider that any of the **merges** performed previously may affect subsequent **merges** (as they are changing many symbol instances and instance overrides).  All of it means that for each **merge** Merge Duplicates has to re-process all of the 40K symbol instances in your document.

Processing all of the 40K symbol instances for each duplicate (there are duplicate symbols in your file) is what is taking a lot of time and resources (CPU and memory). And if it exceeds what the app and OS can handle (depends on your device), Sketch will crash.

### So, what next?

As I mentioned, I'd suggest to split the overall merge into smaller groups. This will reduce the amount of processing Merge Duplicates requires, and hopefully will be able to complete the merge successfully.

On our side, we'll continue to improve the merge process performance. I'll make sure to let you know if we release a relevant fix related to it.


Hope it helps!

**Comment by vegadesign** [comment]
Hi @oodesign 

I have crash cases as well - when I click any action in the plug-in, it crashes and the Sketch closes. The operation system is BigSur and M1 chip. The log file cannot be sent, I can't open the Settings to enable it.

Any ideas on how to resolve this issue?

Thank you

**Comment by oodesign** [comment]
Hi @vegadesign ,

This is somewhat strange. Can't you access the Settings menu in your plugins dropdown?

![Screenshot 2021-01-15 at 07 45 19](https://user-images.githubusercontent.com/11992834/104691105-ec8c4200-5705-11eb-9426-c296fac2f10c.png)
![Screenshot 2021-01-15 at 07 45 29](https://user-images.githubusercontent.com/11992834/104691112-eeee9c00-5705-11eb-9208-21d1bea01590.png)

**Comment by vegadesign** [comment]
@oodesign no, can't do this. When I click the "Settings" menu item, the Sketch (v.70.3) closes:
![image](https://user-images.githubusercontent.com/8604229/104708739-be6b2a00-5726-11eb-9e8e-7015dd320152.png)

**Comment by oodesign** [comment]
Hi @vegadesign ,

This feels really strange. May I suggest a clean install (uninstall Merge Duplicates from the Preferences > Plugins list), and install it again? You may [find the latest version (v8.2.0) here](https://github.com/oodesign/merge-duplicate-symbols/releases). 

If the issue persists, may I ask you to [create a new issue about it](https://github.com/oodesign/merge-duplicate-symbols/issues/new/choose), so that we can continue this conversation there?

Thank you!

**Comment by vegadesign** [comment]
@oodesign re-install does not help. I have created a separate ticket https://github.com/oodesign/merge-duplicate-symbols/issues/132
