### ISSUE TITLE
Replacement Fails on Sketch 51

### ISSUE THREAD

**Issue by ninzucchi** [oodesign/merge-duplicate-symbols#27]
Plugin UI closes and replacement fails after clicking "OK." Using Sketch 51 and a fairly large file. Logs below :

---

default	16:12:56.176116 -0700	Sketch Beta	Exception: TypeError: currentOverrides[keyIndex].allKeys is not a function. (In 'currentOverrides[keyIndex].allKeys()', 'currentOverrides[keyIndex].allKeys' is undefined)

default	16:12:56.176217 -0700	Sketch Beta	TypeError: currentOverrides[keyIndex].allKeys is not a function. (In 'currentOverrides[keyIndex].allKeys()', 'currentOverrides[keyIndex].allKeys' is undefined)
line: 46
sourceURL: /Users/ninzucchi/Library/Application Support/com.bohemiancoding.sketch3/Plugins/MergeDuplicateSymbols.sketchplugin/Contents/Sketch/MergeDuplicateSymbols.cocoascript
column: 79

default	16:12:56.342440 -0700	Sketch Beta	Error in command 3rdPartyPlugins Script at path /Users/ninzucchi/Library/Application Support/com.bohemiancoding.sketch3/Plugins/FB SketchKit.sketchplugin/Contents/Sketch/Analytics/3rdPartyPlugins.cocoascript does not contain a handler function named: onRunPluginCommand.

**Comment by stdk00** [comment]
yup having the same problem under sketch 51.1 replacements aren't working

**Comment by oodesign** [comment]
Hi!

Sad to hear you're having issues with the plugin... we'll do our best to fix it as soon as possible.

Meanwhile, would it be possible to have one of those files you work with to run some tests and debugging on our own? Feel free to remove anything that you wouldn't like to share, but keeping the nested symbols or instances...

Thank you!

**Comment by oodesign** [comment]
Hi @ninzucchi and @stdk00,

We haven't been able to reproduce the issue you're describing.
May you send us the affected files to run some tests on our own? Feel free to remove anything that you wouldn't like to share (keeping the symbols and removing its content is fine too). Just make sure that the affected symbols, nested symbols or instances are there...

Thanks!

**Comment by stdk00** [comment]
@oodesign thanks for putting time on this. I'll try to put together a file, although the behavior is very erratic. sometimes it works, sometimes it doesn't. so i completely understand how hard it will be to replicate this. sometimes it even ignores some symbols that are duplicated. i'm trying to figure out the pattern.

In the meantime is there some other information that might help you out?

thanks a lot

**Comment by oodesign** [comment]
Thank you for arranging a sample file, @stdk00, that will definetely help figure out the problem :)

By the way... may we have a list of your currently installed plugins? Have you noticed if Merge Duplicates Symbols started failing after installing a specific plugin? In the past we've had some issues with plugins (like Diya) that include some wrappers to symbols, changing its internal definition.

Thank you!

**Comment by stdk00** [comment]
these are the only plugins i use:
![pluginlist](https://user-images.githubusercontent.com/6796248/43316975-03f1f36c-9193-11e8-9887-b9ec3929ecaa.png)

it became more erratic when i've updated to sketch 51, but today is working good. i work with very large files with a lot of nested symbols and the issue just happens from time to time so it will be very hard to replicate or isolate in a file.

**Comment by amchap** [comment]
I'm having the same problem. What I have observed is that when it quits on the merge of a certain symbol, it quits on the same symbol the next time I try.

**Comment by oodesign** [comment]
Hi @amchap !
Do you have a specific symbol that always causes the plugin to crash? May you create a new Sketch files with that symbol and a new symbol with the same name, ant try to run the plugin?

Or further than this... may you send us the Sketch file with that symbol to run some tests and debugging on our own?

Thank you!

**Comment by oodesign** [comment]
Thank you @stdk00! 

It will definetely help us understand what's going wrong.
We'll let you know when we find the issue and realease a fix for that.

Thank you!

**Comment by oodesign** [comment]
Hello! @ninzucchi @stdk00 @amchap 

We just released version 3.0.8, which hopefully solves the issues causing the plugin to crash and do apparently nothing.
We've been running it all over our unit tests and everything seems to work fine and performant, but please, try it out and let us know if you still have any issues.

Thanks you all again for the feedback and reporting the issues :)

**Comment by stdk00** [comment]
@oodesign nice, that was fast! I've tested and it's working. if something else comes up i'll let you know. Thank you so much for your time.

**Comment by oodesign** [comment]
@stdk00 Having that case to test & debug really helped! 
Happy it works again for you! :)

**Comment by ninzucchi** [comment]
Thanks everyone! Another magic moment on GH

On August 2, 2018 at 12:35:47 AM, Oscar Oto (notifications@github.com)
wrote:

@stdk00 <https://github.com/stdk00> Having that case to test & debug really
helped!
Happy it works again for you! :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/oodesign/merge-duplicate-symbols/issues/27#issuecomment-409834962>,
or mute the thread

**Comment by stdk00** [comment]
@oodesign hi all. I hate to give bad news but I must say that the problem is still there. the plugin update solved it for a while, but it's back again and it's exactly as before.  I haven't installed any new plugins or sketch updates. its the same configuration i had previously. :(

**Comment by oodesign** [comment]
@stdk00 Sad to hear it's failing again!

May you send us a sample Sketch file, or attach the plugin output log?

Thank you!

**Comment by stdk00** [comment]
@oodesign how can i send you the plugin output log? sorry i have never done that before

**Comment by oodesign** [comment]
@stdk00 Probably the easiest way is that you run the plugin as a script and send us the log.
In Sketch, under the Plugins menu you'll find a "Run Script" option (⌃+⬆️+K).

Copy the plugin raw code from [here](https://github.com/oodesign/merge-duplicate-symbols/blob/master/RawCode) and paste it in the first big text box. Then, click Run.

If everything works fine, nothing should appear in the second box (result). If there's any exception copy the exception text in it and send it over to us :)

Thank you!

**Comment by stdk00** [comment]
@oodesign here you go:

`TypeError: currentOverrides[keyIndex].allKeys is not a function. (In 'currentOverrides[keyIndex].allKeys()', 'currentOverrides[keyIndex].allKeys' is undefined)
line: 52
sourceURL: /Users/rafaelmatosdasilva/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin
column: 83
stack: MergeSymbols@/Users/rafaelmatosdasilva/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:52:83
onRun@/Users/rafaelmatosdasilva/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:354:21


Script executed in 6.178903s`

**Comment by oodesign** [comment]
@stdk00 Thanks!

May you please grab [the raw code](https://github.com/oodesign/merge-duplicate-symbols/blob/master/RawCode) again (we've added a few changes), run it with "Run Script", and send us the result?

#RemoteDebugging :D 

Thank you!

**Comment by stdk00** [comment]
:D

Here it is

`'CurrentOverrides: {\n    "518D7B50-E6A3-4929-B3C1-CABFA34DDF7D" =     {\n        symbolID = "40D159A7-BAC7-4A67-AD66-50BE32F6E00C";\n    };\n    "5F06DDE3-6288-4DAA-BFB5-646F27D7FE2B" = "\\Ue639";\n    "CB37FB6A-BAA7-4512-B6C9-9760734ED0B9" = "Cr\\U00e9dito Sal\\U00e1rio";\n}'
'KeyIndex: 5F06DDE3-6288-4DAA-BFB5-646F27D7FE2B'
'currentOverrides[keyIndex]: '
TypeError: currentOverrides[keyIndex].allKeys is not a function. (In 'currentOverrides[keyIndex].allKeys()', 'currentOverrides[keyIndex].allKeys' is undefined)
line: 55
sourceURL: /Users/rafaelmatosdasilva/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin
column: 83
stack: MergeSymbols@/Users/rafaelmatosdasilva/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:55:83
onRun@/Users/rafaelmatosdasilva/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:357:21


Script executed in 5.053146s`

**Comment by oodesign** [comment]
@stdk00 It seems there are Unicode characters in the override identifiers that shouldn't be there.
I'm afraid it won't get easy to remotely debug why this is happening, and don't like bothering you with this kind of stuff. May you [send us](mailto:oodesignux@gmail.com) a copy of your Sketch file* so that we can run further testing on our own?

(*) Obviously we won't share it in any way. Also, feel free to remove anything else from it (we just need the affected symbol).

Thank you!

**Comment by stdk00** [comment]
@oodesign here is the file for you to test.
[DuplicateIssue.sketch.zip](https://github.com/oodesign/merge-duplicate-symbols/files/2270731/DuplicateIssue.sketch.zip)

let me know if you need anything else.
Thanks a lot!

**Comment by oodesign** [comment]
@stdk00 Awesome! 
We'll make sure to let you know when we find the issue and release a fix.

Thank you!

**Comment by oodesign** [comment]
@stdk00 Hi! We just released v3.0.9, that solves some of the issues.

Anyway, I'd like to ask you... is there any symbol (or layer, or other element) in your Sketch file (or the original Sketch file) named or containing the text "Crédito Salario"?

It appears in our logs as an existing element in the file, but haven't been able to find it exploring the design file... and that worries us :)

Thank you!

**Comment by stdk00** [comment]
@oodesign yup, in the original file there was an override containing that text.
I've tested the new plugin update and its been working good.

Thank you so much for fixing this.
